[package]
name = "tts"
version = "0.6.3"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
repository = "https://github.com/ndarilek/tts-rs"
description = "High-level Text-To-Speech (TTS) interface"
license = "MIT"
exclude = ["*.cfg", "*.yml"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
lazy_static = "1"
log = "0.4"
thiserror = "1"

[dev-dependencies]
env_logger = "0.7"

[target.'cfg(windows)'.dependencies]
tolk = "0.2"
winrt = "0.7"
tts_winrt_bindings = { version = "0.1", path="winrt_bindings" }

[target.'cfg(target_os = "linux")'.dependencies]
speech-dispatcher = "0.6"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
cocoa-foundation = "0.1"
libc = "0.2"
objc = "0.2"
procspawn = "0.9"
ipc-channel = "0.14"
serde = { version = "1.0", features = ["derive"] }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["SpeechSynthesis", "SpeechSynthesisUtterance", "Window", ] }
